CREATE TABLE ALUNO(
	MATRICULA VARCHAR(10),
	NOME VARCHAR(100),
	NOME_MAE VARCHAR(100),
	NOME_PAI VARCHAR(100),
	CEP VARCHAR(8),
	ENDERECO VARCHAR(100),
	DATA_NASCIMENTO DATE
);

CREATE TABLE PROFESSOR(
	MATRICULA VARCHAR(10),
	NOME VARCHAR(50),
	CPF VARCHAR(11),
	SEXO VARCHAR(10)
);

CREATE TABLE DISCIPLINA(
	CODIGO VARCHAR(10),
	NOME VARCHAR(20)
);

CREATE TABLE TURMA(
	CODIGO VARCHAR(10),
	MATRIC_PROFESSOR VARCHAR(10),
	SERIE NUMBER,
	ANO NUMBER
);

CREATE TABLE ALUNOS_EM_TURMAS(
	COD_TURMA VARCHAR(10),
	MATRIC_ALUNO VARCHAR(10)
);

CREATE TABLE DISCIPLINA_EM_TURMAS(
	COD_DISCIPLINA VARCHAR(10),
	COD_TURMA VARCHAR(10)
)

SELECT A.MATRICULA, A.NOME
FROM ALUNO A, ALUNOS_EM_TURMAS AT
WHERE AT.COD_TURMA = [codigo da turma]
AND AT.MATRIC_ALUNO = A.MATRICULA